name: Run Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.14.3'

            - name: Install uv
              uses: astral-sh/setup-uv@v7

            - name: Install dependencies
              run: uv sync --extra test

            - name: Cache trained model
              id: cache-model
              uses: actions/cache@v3
              with:
                path: models/
                key: model-${{ hashFiles('training/train.py') }}

            - name: Download Titanic dataset
              run: |
                mkdir -p data
                curl -L https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv \
                -o data/titanic.csv

            - name: Train model
              if: steps.cache-model.outputs.cache-hit != 'true'
              env:
                DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
              run: |
                uv run python training/train.py

            - name: Validate model
              run: |
                uv run python training/validate.py

            - name: Run tests
              run: |
                uv run pytest tests/

            - name: Upload model to DagsHub
              if: steps.cache-model.outputs.cache-hit != 'true'
              env:
                DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
              run: |
                uv run dvc push